[package]
name = "enola"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
futures = "0.3.31"
regex = "1.11.2"
reqwest = "0.12.23"
scraper = "0.24.0"
serde = "1.0.219"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
